"""Initial migration

Revision ID: 2e81a303a506
Revises: 
Create Date: 2022-03-10 19:49:35.377268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e81a303a506'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('pressure_reading', sa.JSON(), nullable=False),
    sa.Column('is_zero', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_readings')
    # ### end Alembic commands ###
